import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import Footer from "./components/footer";
import BootstrapScripts from "./components/BootstrapScripts";
import "bootstrap-icons/font/bootstrap-icons.css";
import Navarbar from "./components/Navarbar";

const geist = Geist({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-geist",
});

const geistMono = Geist_Mono({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-geist-mono",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geist.variable} ${geistMono.variable}`}>
      <body>
        <div className="container-fluid">
          <Navarbar />

          {children}
          <BootstrapScripts />
          <Footer />
        </div>
      </body>
    </html>
  );
}
