import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import Footer from "./components/footer";
import BootstrapScripts from "./components/BootstrapScripts";
import "bootstrap-icons/font/bootstrap-icons.css";
import Navarbar from "./components/Navarbar";

import { Sarabun } from "next/font/google";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="th" className={sarabun.variable}>
      <body>
        <div className="container-fluid">
          <Navarbar />

          {children}
          <BootstrapScripts />
          <Footer />
        </div>
      </body>
    </html>
  );
}
